file(REMOVE_RECURSE "${WORK}")
file(MAKE_DIRECTORY "${WORK}")
foreach(pass RANGE 1 2)
  execute_process(COMMAND "${EXAMPLE}" "${WORK}/live" RESULT_VARIABLE result)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Persistent example failed")
  endif()
endforeach()
foreach(operation backup restore)
  if(operation STREQUAL "backup")
    set(source "${WORK}/live")
  else()
    set(source "${WORK}/backup")
  endif()
  execute_process(COMMAND "${ADMIN}" ${operation} "${source}" "${WORK}/${operation}" RESULT_VARIABLE result)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "${operation} failed")
  endif()
endforeach()
execute_process(COMMAND "${ADMIN}" backup "${WORK}/live" "${WORK}/backup" RESULT_VARIABLE result)
if(result EQUAL 0)
  message(FATAL_ERROR "Backup overwrote an existing destination")
endif()
file(WRITE "${WORK}/check.sql" "SELECT body FROM notes WHERE id=1;")
execute_process(COMMAND "${CLI}" --database "${WORK}/restore" "${WORK}/check.sql" RESULT_VARIABLE result OUTPUT_VARIABLE output)
if(NOT result EQUAL 0 OR NOT output STREQUAL "Persistent hello\n")
  message(FATAL_ERROR "Restore contents differ: ${output}")
endif()
