string(RANDOM LENGTH 12 ALPHABET abcdef0123456789 suffix)
set(directory "${WORK}-${suffix}")
if(EXISTS "${directory}")
  message(FATAL_ERROR "Test directory collision")
endif()
file(MAKE_DIRECTORY "${directory}")
set(database "${directory}/documents.core")
function(run expected fragment)
  execute_process(COMMAND "${EXE}" "${database}" ${ARGN}
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT result STREQUAL "${expected}")
    message(FATAL_ERROR "Unexpected exit ${result}: ${output}${error}")
  endif()
  string(FIND "${output}${error}" "${fragment}" position)
  if(position EQUAL -1)
    message(FATAL_ERROR "Missing '${fragment}' in: ${output}${error}")
  endif()
endfunction()
run(1 "Database does not exist" list)
if(EXISTS "${database}")
  message(FATAL_ERROR "Reading a missing database created a file")
endif()
run(0 "Reopened after update and deletion" demo)
run(1 "requires a new" demo)
run(0 "3 embedding dimensions" info)
run(0 "Revised recovery checklist" get 3)
run(0 "Storage journal notes" nearest 1,0,0 1)
run(0 "Revised recovery checklist" list 10 350)
run(0 "Inserted" put 4 500 0,1,0 "New document with spaces")
run(0 "Updated" put 4 600 0,1,0 "Revised document with spaces")
run(0 "Revised document with spaces" get 4)
run(1 "dimension differs" put 4 700 1,2 "Invalid replacement")
run(0 "Revised document with spaces" get 4)
run(1 "finite" nearest nan,0,0)
run(1 "nonnegative" list -1)
run(1 "Expected comma-separated" nearest 1,,0)
run(0 "Deleted" delete 4)
run(0 "Not found" delete 4)
run(0 "No matching" get 4)
file(REMOVE_RECURSE "${directory}")
